/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class frame_login extends javax.swing.JFrame {

    /**
     * Creates new form frame_login
     */
    public frame_login() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon picture= new ImageIcon("src/images/logo.jpg");
        Icon icon= new ImageIcon(picture.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_password = new javax.swing.JLabel();
        tfd_user = new javax.swing.JTextField();
        lbl_user1 = new javax.swing.JLabel();
        tfd_password = new javax.swing.JPasswordField();
        btn_access = new javax.swing.JButton();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_password.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbl_password.setText("Password");
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 114, 24));
        getContentPane().add(tfd_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 140, 33));

        lbl_user1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbl_user1.setText("User Name");
        getContentPane().add(lbl_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 114, 24));

        tfd_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(tfd_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 140, 35));

        btn_access.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btn_access.setText("Enter");
        btn_access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accessActionPerformed(evt);
            }
        });
        getContentPane().add(btn_access, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 140, 30));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accessActionPerformed

        
            frame_start start= new frame_start();
            start.setVisible(true);
            this.setVisible(false);
            
        
    }//GEN-LAST:event_btn_accessActionPerformed

    private void tfd_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_access;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_user1;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JPasswordField tfd_password;
    private javax.swing.JTextField tfd_user;
    // End of variables declaration//GEN-END:variables
}
