/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Domain.Student;
import File.StudentFile;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class frame_student extends javax.swing.JFrame {

    /**
     * Creates new form frame_student
     */
    public frame_student() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon picture= new ImageIcon("src/images/Pre.jpg");
        Icon icon= new ImageIcon(picture.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_name = new javax.swing.JLabel();
        lbl_lastname = new javax.swing.JLabel();
        lbl_residence = new javax.swing.JLabel();
        lbl_carrer = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        txf_lastname = new javax.swing.JTextField();
        txf_name = new javax.swing.JTextField();
        txf_recidence = new javax.swing.JTextField();
        txf_year = new javax.swing.JTextField();
        btn_return = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        cb_selectedCarreer = new javax.swing.JComboBox<>();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 555));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lbl_name.setText("Name");
        getContentPane().add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 34, 60, 30));

        lbl_lastname.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lbl_lastname.setText("Last Name");
        getContentPane().add(lbl_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 100, 20));

        lbl_residence.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lbl_residence.setText("Residence");
        getContentPane().add(lbl_residence, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 194, 70, 20));

        lbl_carrer.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lbl_carrer.setText("Carrer");
        getContentPane().add(lbl_carrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, 20));

        lbl_year.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lbl_year.setText("Year");
        getContentPane().add(lbl_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 40, 20));

        txf_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(txf_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 280, 30));

        txf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 280, 30));

        txf_recidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_recidenceActionPerformed(evt);
            }
        });
        getContentPane().add(txf_recidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 280, 30));

        txf_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_yearActionPerformed(evt);
            }
        });
        getContentPane().add(txf_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 280, 30));

        btn_return.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btn_return.setText("Return");
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 90, 30));

        btn_insert.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btn_insert.setText("Insert");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        getContentPane().add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 280, 30));

        cb_selectedCarreer.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cb_selectedCarreer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informática", "Agronomía", "Educación" }));
        getContentPane().add(cb_selectedCarreer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 280, 30));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_lastnameActionPerformed

    private void txf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nameActionPerformed

    private void txf_recidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_recidenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_recidenceActionPerformed

    private void txf_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_yearActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        File file= new File("./student.dat");
        
        try{
            StudentFile fileStudent= new StudentFile(file);
        // capturar los datos 
        String nameS = txf_name.getText();
        String lastnameS = txf_lastname.getText();
        String recidenceS = txf_recidence.getText();
        String carrerS = cb_selectedCarreer.getSelectedItem().toString();
        int yearS = Integer.parseInt(txf_year.getText());
        String idS=carrerS.substring(0, 1)+yearS%10+fileStudent.secuence();
        //se inserta el student pero se verifica que llene todos los espacios 
        
        
        if(!txf_name.getText().equalsIgnoreCase("")&&!txf_lastname.getText().equalsIgnoreCase("")&&!txf_recidence.getText().equalsIgnoreCase("")){
            Student student = new Student(nameS, lastnameS, recidenceS, carrerS, yearS, idS);
            fileStudent.addEndRecord(student);
            JOptionPane.showMessageDialog(null, "Su carne es: "+idS);
        }
        else
            JOptionPane.showMessageDialog(null,"Llene todos espacios");
        //resetea los campos de textos
        txf_lastname.setText("");
        txf_name.setText("");
        txf_recidence.setText("");
        txf_year.setText("");
        cb_selectedCarreer.setSelectedIndex(0);
        
        }catch(IOException ioe){
            System.out.println("Error-1003");
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "LLene todos los espacios y verifique que ingreso numeros en los espacios correctos");
        }
        
        
        
    }//GEN-LAST:event_btn_insertActionPerformed
    
    public Student[] idVectorStudent() throws IOException{
        File file= new File("./student.dat");
        StudentFile fileStudent= new StudentFile(file);
        ArrayList<Student> arrayOfStudent= fileStudent.getStudentList();
        Student vector[] = new Student[arrayOfStudent.size()];
        for (int i = 0; i < arrayOfStudent.size(); i++) {
            vector[i]=arrayOfStudent.get(i);
            
        }
       
    return vector;
    }
    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // desabilita la ventana actual y pasa a la otra interfaz deseada
        frame_start start_frame= new frame_start();
        start_frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_return;
    private javax.swing.JComboBox<String> cb_selectedCarreer;
    private javax.swing.JLabel lbl_carrer;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_residence;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JTextField txf_lastname;
    private javax.swing.JTextField txf_name;
    private javax.swing.JTextField txf_recidence;
    private javax.swing.JTextField txf_year;
    // End of variables declaration//GEN-END:variables
}
